"""Add provider_id, consumer_id to session

Revision ID: dc4714452e50
Revises: 9f7a13ec4cef
Create Date: 2018-01-11 14:46:38.605900

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dc4714452e50'
down_revision = '9f7a13ec4cef'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('session', sa.Column('provider_id', sa.String(length=42), nullable=True))
    op.add_column('session', sa.Column('consumer_id', sa.String(length=42), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('session', 'consumer_id')
    op.drop_column('session', 'provider_id')
    # ### end Alembic commands ###
